language: node_js

node_js: node

addons:
  apt:
    packages:
      - libgconf-2-4 # needed for Ubuntu 16+

cache:
  yarn: true
  directories:
    - ~/.cache # contains the Cypress binary

script: yarn lint && yarn test && yarn start & wait-on http://localhost:3000/ && $(yarn bin)/percy exec -t 10000 -- $(yarn bin)/cypress run --spec 'cypress/integration/ci/*' --record
