language: node_js

node_js: node

addons:
  apt:
    packages:
    - libgconf-2-4

script: yarn lint && yarn test && yarn start & percy exec -- $(yarn bin)/cypress run --spec 'cypress/integration/ci/*' --record
