name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Jest
        run: yarn test

      - name: TypeScript
        run: yarn tsc

      - name: Cypress
        run: yarn start & wait-on http://localhost:3000/ && $(yarn bin)/percy exec -- $(yarn bin)/cypress run --spec 'cypress/integration/ci/*' --record
