name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('yarn.lock') }}

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Jest
        run: yarn test

      - name: TypeScript
        run: yarn tsc

      - name: Start
        run: yarn start & wait-on http://localhost:3000/

      - name: Cypress
        run: $(yarn bin)/percy exec -- $(yarn bin)/cypress run --spec 'cypress/integration/ci/*' --record
